import test from 'node:test';
import assert from 'node:assert/strict';
import {createHmac} from 'node:crypto';
import {maxProfile,maxUser,validatePlan,eventAllowedForUser,validateAge} from '../server/domain.js';
test('unknown age permits onboarding but never age-restricted events',()=>{const user={registered:true,profile:{age:null}};assert.equal(eventAllowedForUser({age:null},user),true);assert.equal(eventAllowedForUser({age:'18+'},user),false);assert.equal(eventAllowedForUser({annotation:{facts:{minimumAge:7}}},user),false);assert.equal(validateAge('23'),23);for(const age of [null,0,6,101,12.5,'bad'])assert.throws(()=>validateAge(age));});
test('MAX WebAppData HMAC rejects tampering and expired sessions',()=>{const token='test-only-token',now=Date.now();const q=new URLSearchParams({auth_date:String(Math.floor(now/1000)),user:JSON.stringify({id:42,first_name:'Тест'})});const str=[...q.entries()].sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>`${k}=${v}`).join('\n');const key=createHmac('sha256','WebAppData').update(token).digest();q.set('hash',createHmac('sha256',key).update(str).digest('hex'));assert.equal(maxUser(q.toString(),token,now).id,'42');assert.throws(()=>maxUser(q.toString(),token,now+3700000));q.set('user',JSON.stringify({id:43}));assert.throws(()=>maxUser(q.toString(),token,now));});
test('MAX profile supplies a safe name and optional HTTPS avatar',()=>{assert.deepEqual(maxProfile({first_name:' Маша ',photo_url:'https://example.org/avatar.jpg'}),{firstName:'Маша',photoUrl:'https://example.org/avatar.jpg'});assert.equal(maxProfile({first_name:'Маша',photo_url:'javascript:alert(1)'}).photoUrl,null);assert.equal(maxProfile({first_name:'Маша',photo_url:null}).photoUrl,null);});
test('Unknown, expired and out-of-period visits rejected',()=>{const now=Date.parse('2026-09-16T12:00:00Z'),e={startsAt:'2026-01-01',endsAt:'2026-12-31'};assert.throws(()=>validatePlan({},null,now));assert.throws(()=>validatePlan({when:'bad'},e,now));assert.throws(()=>validatePlan({when:'2027-01-01'},e,now));assert.throws(()=>validatePlan({}, {...e,endsAt:'2026-09-01'},now));assert.equal(validatePlan({when:'2026-09-20T10:00:00Z',confirmed:true},e,now).confirmed,true);});
test('semantic quality hides unsafe and rejected cards from users',()=>{const user={registered:true,profile:{age:25}};assert.equal(eventAllowedForUser({age:null,annotation:{quality:{status:'suitable'}}},user),true);assert.equal(eventAllowedForUser({age:null,annotation:{quality:{status:'hidden'}}},user),false);assert.equal(eventAllowedForUser({age:null,annotation:{quality:{status:'human_review'}}},user),false);});
