import {botReply} from './domain.js';
const pause=ms=>new Promise(r=>setTimeout(r,ms));
export async function telegramCall(token,method,data){const r=await fetch(`https://api.telegram.org/bot${token}/${method}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data),signal:AbortSignal.timeout(40000)});const result=await r.json();if(!result.ok)throw new Error(`Telegram ${method}: ${result.error_code}`);return result.result;}
export async function startBot({token,appUrl,store,catalog}){
 const send=(id,text,extra={})=>telegramCall(token,'sendMessage',{chat_id:id,text,...extra});
 setInterval(async()=>{for(const p of store.plans()){const u=store.user(p.owner);const delta=Date.parse(p.when)-Date.now();if(p.status==='ready'&&u?.reminders&&u.chatId&&!p.reminded&&delta>0&&delta<=24*3600000){try{await send(u.chatId,`Завтра или сегодня твой первый шаг: ${catalog.find(e=>e.id===p.eventId)?.title}. Проверь время и место в плане. Если планы поменялись, можно отменить без чувства вины.`,{reply_markup:{inline_keyboard:[[{text:'Мой план',web_app:{url:appUrl+'/?tab=plan'}}]]}});p.reminded=true;store.savePlan(p);}catch{console.error('Reminder delivery failed; retry next minute.');}}}},60000).unref();
 while(true){try{const updates=await telegramCall(token,'getUpdates',{offset:Number(store.meta('offset')||0),timeout:25,allowed_updates:['message']});for(const update of updates){const m=update.message;if(m?.chat?.type==='private'&&m.from&&!m.from.is_bot){const id=`tg:${m.from.id}`;let u=store.user(id)||{id,name:m.from.first_name,profile:{city:'Москва',category:'all',barrier:'company'},reminders:false};u.chatId=m.chat.id;store.saveUser(u);const text=m.text||'';let reply=botReply(text,u.name);const command=text.split(/[ @]/)[0];let link=appUrl;
 if(command==='/delete'){store.deleteUser(id);await send(m.chat.id,'Твои планы и профиль удалены. /start — начать заново.');}
 else{if(command==='/stop'){u.reminders=false;store.saveUser(u);}if(command==='/plan'){const p=store.plans().find(p=>(p.owner===id||p.members.some(v=>v.id===id))&&!['cancelled','done'].includes(p.status));reply=p?`Твой план: ${catalog.find(e=>e.id===p.eventId)?.title}. ${p.when?new Date(p.when).toLocaleString('ru-RU',{timeZone:'Europe/Moscow'})+' (Москва)':'Дата пока не согласована'}. ${p.confirmed?'Ты отметил согласование с организатором.':'Сначала свяжись с организатором.'}`:'Пока нет плана. Можно начать с одного небольшого дела.';link+='/?tab=plan';}const code=text.match(/^\/start(?:@\w+)? i_([a-f0-9]{36})$/)?.[1];if(code){link+=`/?invite=${code}`;reply='Тебя пригласили сделать первый шаг вместе. Посмотри дело и присоединись, если тебе подходит. Личная встреча появится в плане после принятия приглашения.';}await send(m.chat.id,reply,{reply_markup:{inline_keyboard:[[{text:code?'Посмотреть приглашение':'Открыть «Первый шаг»',web_app:{url:link}}]]}});}}
 store.setMeta('offset',update.update_id+1);}}catch{console.error('Telegram connection failed; retry in 5s.');await pause(5000);}}
}
